# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Maven@3
          displayName: 'Maven pom.xml'
          inputs:
            mavenPomFile: '$(Parameters.mavenPOMFile)'
        - task: Docker@2
          displayName: buildAndPush
          inputs:
            containerRegistry: Dockerhub
            Dockerfile: Dockerfile